config/routes.rb
XnotY::Application.routes.draw do
  resources :invites, :only => [:destroy, :show]

  resources :responses

  resources :suggestions do
    resources :responses
  end

  resources :users
  
  resources :sms, only: [] do
    collection do
      post :record
    end
  end

  resources :events do
    member do
      post :join
    end

    resources :invites
    resources :suggestions
  end

  resources :geocode, :only => [] do
    collection do
      get :resolve
    end
  end

  resource :welcome, :only => [:index]

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'welcome#index'

  resource :facebook, except: :new do
    get :callback, to: :create
  end

end

app/models/invite.rb
class Invite
  include Mongoid::Document
  include Mongoid::Timestamps

  field :email, type: String
  field :is_active, type: Boolean

  belongs_to :invited_user, class_name: "User"
  
  belongs_to :event
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  respond_to :json, :html

  def index
    @event = Event.find(params[:event_id])
    @invites = Invite.where(event: @event).all

    respond_with @invites
  end

  def show
    @invite = Invite.find(params[:id])
    respond_with @invite
  end

  def create
    @event = Event.find(params[:event_id])
    @invite = Invite.new(params[:invite])
    @invite.event = @event
    respond_to do |format|
      if @invite.save
        format.html { redirect_to @invite, notice: 'Invite was successfully created.' }
        format.json { render json: @invite, status: :created, location: @invite }
      else
        format.html { render action: "new" }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @invite = Invite.find(params[:id])
    # TODO check that the invite belongs to this user

    respond_to do |format|
      if @invite.update_attributes(params[:invite])
        format.html { redirect_to @invite, notice: 'Invite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @invite = Invite.find(params[:id])
    @invite.destroy

    respond_to do |format|
      format.html { redirect_to invites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_form.html.haml
= form_for @invite do |f|
  - if @invite.errors.any?
    #error_explanation
      %h2= "#{pluralize(@invite.errors.count, "error")} prohibited this invite from being saved:"
      %ul
        - @invite.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/invites/edit.html.haml
%h1 Editing invite

= render 'form'

= link_to 'Show', @invite
\|
= link_to 'Back', invites_path

app/views/invites/index.html.haml
%h1 Listing invites

%table
  %tr
    %th
    %th
    %th

  - @invites.each do |invite|
    %tr
      %td= link_to 'Show', invite
      %td= link_to 'Edit', edit_invite_path(invite)
      %td= link_to 'Destroy', invite, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Invite', new_invite_path

app/views/invites/new.html.haml
%h1 New invite

= render 'form'

= link_to 'Back', invites_path

app/views/invites/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_invite_path(@invite)
\|
= link_to 'Back', invites_path