config/routes.rb
XnotY::Application.routes.draw do
  resources :invites, :only => [:destroy, :show]

  resources :responses

  resources :suggestions do
    resources :responses
  end

  resources :users
  
  resources :sms, only: [] do
    collection do
      post :record
    end
  end

  resources :events do
    member do
      post :join
    end

    resources :invites
    resources :suggestions
  end

  resources :geocode, :only => [] do
    collection do
      get :resolve
    end
  end

  resource :welcome, :only => [:index]

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'welcome#index'

  resource :facebook, except: :new do
    get :callback, to: :create
  end

end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :description, type: String
  field :startRange, type: DateTime
  field :endRange, type: DateTime
  field :location, type: String

  belongs_to :user
  has_many :suggestions
  has_many :invites

  def is_user_attending?(user)
    return false if user.nil?
    return true  if is_organizer?(user)
    invite = Invite.where(user_id: user._id, event_id: self._id).first
    !invite.nil?
  end

  def is_organizer?(user)
    user.andand._id == self.user_id
  end

  def attendees
    invites.map(&:invited_user)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  respond_to :html, :json
  def index
    if !signed_in?
      return render json: {success: false}, status: :unauthorized
    end 
    @events = Event.where(user: current_user).all
    @events += Invite.where(invited_user: current_user).all.map(&:event)
    respond_with @events
  end

  def show
    @event = Event.find(params[:id])
    respond_with @event
  end

  def join
    if !signed_in?
      return render json: {success: false}, status: :unauthorized
    end
    @event = Event.find(params[:id])
    if @event.is_user_attending?(current_user)
      return respond_with @event
    end
    @invite = Invite.create!
    @invite.event = @event
    @invite.invited_user = current_user
    @invite.save

    respond_with @event
  end

  def create
    # if user not logged in then return 401
    if !signed_in?
      return render json: {success: false}, status: :unauthorized
    end
    @event = Event.new(params[:event])
    @event.user = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :startRange
    = f.text_field :startRange
  .field
    = f.label :endRange
    = f.text_field :endRange
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1 Listing events

%table
  %tr
    %th Title
    %th Description
    %th

  - @events.each do |event|
    %tr
      %td= link_to event.title, event
      %td= event.description
      %td= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Event', new_event_path

= render :partial => "shared/locu_templates"

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%div#pageContent
%script#eventDetailsTemplate{:charset => "utf-8", :type => "text/x-mustache-template"}
  %p#notice= notice

  %p
    %b Title:
    = @event.title
  %p
    %b Description:
    = @event.description

  %p
    %b Organizer:
    .organizer
      %img{:src => 'https://graph.facebook.com/' + @event.user.facebook_id + '/picture?type=small'}
      = @event.user.easy_name

  %p
    %b Attendees:
    - @event.attendees.each do |attendee|
      .attendee
        %img{:src => 'https://graph.facebook.com/' + attendee.facebook_id + '/picture?type=small'}
        = attendee.easy_name

  .row
    %a.button.radius.button-facebook-send{:href => '#', :'data-fb-send-url' => 'events/' + @event._id.to_s}
      Invite your Facebook friends

%script#eventLoginTemplate{:charset => "utf-8", :type => "text/x-mustache-template"}
  .row
    %a.large.button.radius.button-facebook-connect-join{:href => '#'}
      Join Event with Facebook Connect

%script#eventPhoneNumberTemplate{:charset => "utf-8", :type => "text/x-mustache-template"}
  .row
    %form#phoneNumberForm
      %input#phoneNumberInput{:type => 'text', :placeholder => "Enter Phone Number"}
      %a.large.button.radius.button-phone-connect-join{:href => '#'}
        Submit

%script#invitesTemplate{:charset => "utf-8", :type => "text/x-mustache-template"}
  %div#inviteList

%div#locuLocations.seven.columns
%div#currentLocation.five.columns

%div.fb-comments{:'data-href' => "http://www.xnoty.com/events/#{@event._id}", :'data-num-posts' => "5", :'data-width' => "470"}

= render :partial => "shared/locu_templates"