config/routes.rb
XnotY::Application.routes.draw do
  resources :invites, :only => [:destroy, :show]

  resources :responses

  resources :suggestions do
    resources :responses
  end

  resources :users
  
  resources :sms, only: [] do
    collection do
      post :record
    end
  end

  resources :events do
    member do
      post :join
    end

    resources :invites
    resources :suggestions
  end

  resources :geocode, :only => [] do
    collection do
      get :resolve
    end
  end

  resource :welcome, :only => [:index]

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'welcome#index'

  resource :facebook, except: :new do
    get :callback, to: :create
  end

end

app/models/suggestion.rb
class Suggestion
  include Mongoid::Document
  include Mongoid::Timestamps
  field :description, type: String
  field :location, type: String
  field :time, type: DateTime
  after_create :notify_all
  
  has_many :responses
  belongs_to :user
  belongs_to :event
  has_many :suggestion_messages

  def notify_all
    users = event.invites.map(&:invited_user) + [event.user]
    # don't send to the suggestion creator
    users = users.reject{|u| u._id == self.user._id}.compact
    users.map do |user|
      message = SuggestionMessage.send_message(user, self)
    end
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  respond_to :json, :html

  def index
    @event = Event.find(params[:event_id])
    @suggestions = Suggestion.where(event: @event).all
    respond_with @suggestions
  end

  def show
    @suggestion = Suggestion.find(params[:id])
    respond_with @suggestion
  end

  def create
    @event = Event.find(params[:event_id])
    @suggestion = Suggestion.new(params[:suggestion])
    @suggestion.event = @event

    respond_to do |format|
      if @suggestion.save
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully created.' }
        format.json { render json: @suggestion, status: :created, location: @suggestion }
      else
        format.html { render action: "new" }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @suggestion = Suggestion.find(params[:id])
    # TODO check that the suggestion belongs to this user

    respond_to do |format|
      if @suggestion.update_attributes(params[:suggestion])
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @suggestion = Suggestion.find(params[:id])
    @suggestion.destroy

    respond_to do |format|
      format.html { redirect_to suggestions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/suggestions/_form.html.haml
= form_for @suggestion do |f|
  - if @suggestion.errors.any?
    #error_explanation
      %h2= "#{pluralize(@suggestion.errors.count, "error")} prohibited this suggestion from being saved:"
      %ul
        - @suggestion.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/suggestions/edit.html.haml
%h1 Editing suggestion

= render 'form'

= link_to 'Show', @suggestion
\|
= link_to 'Back', suggestions_path

app/views/suggestions/index.html.haml
%h1 Listing suggestions

%table
  %tr
    %th Description
    %th
    %th
    %th

  - @suggestions.each do |suggestion|
    %tr
      %td= suggestion.description
      %td= link_to 'Show', suggestion
      %td= link_to 'Edit', edit_suggestion_path(suggestion)
      %td= link_to 'Destroy', suggestion, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Suggestion', new_suggestion_path

app/views/suggestions/new.html.haml
%h1 New suggestion

= render 'form'

= link_to 'Back', suggestions_path

app/views/suggestions/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @suggestion.description

= link_to 'Edit', edit_suggestion_path(@suggestion)
\|
= link_to 'Back', suggestions_path